### ISSUE TITLE
Unable to sense unit at location

### ISSUE THREAD

**Issue by hardik124** [battlecode/battlecode-2018#137]
Stacktrace :- 

Error: b'No object returned, check whether it exists first.'
Traceback (most recent call last):
File "run.py", line 202, in <module>
unit_to_attack = bestAttackSquare(unit,location.map_location(), 30);
File "run.py", line 66, in bestAttackSquare
otherUnit = gc.sense_unit_at_location(location_curr)
File "/home/f390/BATTLECODE/bc18-scaffold/battlecode-manager/working_dir/battlecode/python/battlecode/__init__.py", line 4857, in sense_unit_at_location
_check_errors()

**Comment by ygina** [comment]
@hardik124 What version are you currently running? You can find it on the bottom of your web viewer.

**Comment by hardik124** [comment]
0.11.1

**Comment by ygina** [comment]
@hardik124 Please update to 0.13.0
