### ISSUE TITLE
Internal Error: Unreachable Code

### ISSUE THREAD

**Issue by dmhacker** [battlecode/battlecode-2018#93]
Looks like a get() call to the _planet_states_ map is returning None? Here's the stacktrace ...

```
[earth:red] thread '<unnamed>' panicked at 'internal error: entered unreachable code', battlecode-engine/src/world.rs:721:12
[earth:red] stack backtrace:
[earth:red]    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
[earth:red]              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Here?
[earth:red]    1: std::sys_common::backtrace::_print
[earth:red]              at src/libstd/sys_common/backtrace.rs:69
[earth:red]    2: std::panicking::default_hook::{{closure}}
[earth:red]              at src/libstd/sys_common/backtrace.rs:58
[earth:red]              at src/libstd/panicking.rs:381
[earth:red]    3: std::panicking::default_hook
[earth:red]              at src/libstd/panicking.rs:397
[earth:red]    4: std::panicking::rust_panic_with_hook
[earth:red]              at src/libstd/panicking.rs:577
[earth:red]    5: std::panicking::begin_panic
[earth:red]    6: battlecode_engine::world::GameWorld::get_unit
[earth:red]    7: battlecode_engine::world::GameWorld::ok_if_can_attack
[earth:red]    8: battlecode_engine::controller::GameController::can_attack
[earth:red]    9: std::panicking::try::do_call
[earth:red]   10: __rust_maybe_catch_panic
[earth:red]              at src/libpanic_unwind/lib.rs:99
[earth:red]   11: bc_GameController_can_attack
[earth:red]   12: Java_bc_bcJNI_GameController_1canAttack
[earth:red]   13: <unknown>
[earth:red] Exception in thread "main" java.lang.RuntimeException: panic occurred, talk to the devs: internal error: entered unreachable code
[earth:red]     at bc.bcJNI.GameController_canAttack(Native Method)
[earth:red]     at bc.GameController.canAttack(GameController.java:172)
[earth:red]     at RangerController.runTurn(RangerController.java:63)
[earth:red]     at Player.main(Player.java:93)
```

**Comment by dmhacker** [comment]
Fixed in the latest release, so closing.
